from logging.config import fileConfig
from pathlib import Path
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context
import importlib
import importlib.util
import os
import sys

# Add parent directory to path to import models
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

# Import Base and all models
from database import Base
from models import *

# this is the Alembic Config object
config = context.config

# Override sqlalchemy.url with environment variable
config.set_main_option(
    "sqlalchemy.url",
    os.getenv("DATABASE_URL", "postgresql+asyncpg://redwire:changeme@localhost:5432/redwire").replace(
        "+asyncpg", ""
    )  # Use psycopg2 for alembic
)

# ── Plugin migrations discovery ───────────────────────────────────────
#
# Each plugin can ship its own migration history at
# ``plugins/<slug>/alembic/versions/*.py``. We collect those directories
# and hand them to Alembic via ``version_locations`` so ``alembic upgrade
# heads`` (plural) advances every branch — core + one per plugin.
#
# Each plugin's initial migration should declare a branch label
# (typically ``branch_labels = ("plugin:<slug>",)`` and ``down_revision =
# None``) so the branches stay disjoint from core history. Later
# migrations in the same plugin chain reference their own predecessors
# only.
#
# We also import each plugin's ``models`` module (if present) so autogen
# can see plugin-defined tables. Import errors are logged but not fatal
# — a broken plugin shouldn't stop core upgrades.
_BACKEND_DIR = Path(__file__).resolve().parent.parent  # backend/
_CORE_VERSIONS = _BACKEND_DIR / "alembic" / "versions"

def _discover_plugin_migration_dirs() -> list[Path]:
    plugins_root = _BACKEND_DIR / "plugins"
    dirs: list[Path] = []
    if not plugins_root.is_dir():
        return dirs
    for entry in sorted(plugins_root.iterdir()):
        if not entry.is_dir() or entry.name.startswith((".", "_")):
            continue
        vdir = entry / "alembic" / "versions"
        if vdir.is_dir():
            dirs.append(vdir)
    return dirs


def _import_plugin_models() -> None:
    """Best-effort import of ``plugins/<slug>/models.py`` so autogen
    can see plugin-defined tables. Skips silently if the module is
    absent; logs (stderr) if it errors during import."""
    plugins_root = _BACKEND_DIR / "plugins"
    if not plugins_root.is_dir():
        return
    for entry in sorted(plugins_root.iterdir()):
        if not entry.is_dir() or entry.name.startswith((".", "_")):
            continue
        models_path = entry / "models.py"
        if not models_path.exists():
            continue
        mod_name = f"plugins.{entry.name}.models"
        try:
            spec = importlib.util.spec_from_file_location(
                mod_name, str(models_path),
                submodule_search_locations=[str(entry)],
            )
            mod = importlib.util.module_from_spec(spec)
            sys.modules[mod_name] = mod
            spec.loader.exec_module(mod)
        except Exception as e:
            print(f"[alembic env] plugin '{entry.name}' models import failed "
                  f"(non-fatal): {e}", file=sys.stderr)

_plugin_version_dirs = _discover_plugin_migration_dirs()
_import_plugin_models()

if _plugin_version_dirs:
    # Alembic reads ``version_locations`` from config as a space-separated
    # list (per alembic docs). Include the core dir first so autogenerated
    # new migrations without --branch-label default to the core branch.
    all_locations = [str(_CORE_VERSIONS)] + [str(p) for p in _plugin_version_dirs]
    config.set_main_option("version_locations", " ".join(all_locations))

# Interpret the config file for Python logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set target metadata for autogenerate
target_metadata = Base.metadata

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()

def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
