"""overhaul_findings_and_add_templates

Revision ID: 88a062fc30df
Revises: ce0d66f1543c
Create Date: 2026-01-25 05:10:16.942584+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a062fc30df'
down_revision: Union[str, None] = 'ce0d66f1543c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_assets',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'asset_id')
    )
    op.add_column('findings', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('findings', sa.Column('technical_details', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('mitigations', sa.Text(), nullable=True))
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.drop_column('findings', 'affected_asset')
    op.drop_column('findings', 'remediation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('remediation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('affected_asset', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_column('findings', 'mitigations')
    op.drop_column('findings', 'technical_details')
    op.drop_column('findings', 'category')
    op.drop_table('finding_assets')
    # ### end Alembic commands ###
