"""add_infra_vault_items_and_access_tables

Revision ID: b11b2a991776
Revises: a1b2c3d4e5g0
Create Date: 2026-03-27 18:21:46.482643+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b11b2a991776'
down_revision: Union[str, None] = 'a1b2c3d4e5g0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = inspector.get_table_names()

    def _index_names(table):
        return {idx['name'] for idx in inspector.get_indexes(table)}

    def _fk_names(table):
        return {fk['name'] for fk in inspector.get_foreign_keys(table)}

    if 'infra_vault_access' not in existing:
        op.create_table('infra_vault_access',
        sa.Column('infra_item_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('granted_by', sa.String(), nullable=True),
        sa.Column('granted_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['infra_item_id'], ['infra_items.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('infra_item_id', 'user_id')
        )
    if 'infra_vault_items' not in existing:
        op.create_table('infra_vault_items',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('infra_item_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('item_type', sa.String(length=100), nullable=False),
        sa.Column('username', sa.Text(), nullable=True),
        sa.Column('password', sa.Text(), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('file_path', sa.String(length=500), nullable=True),
        sa.Column('filename', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_infra_vault_items_infra_item_id'), 'infra_vault_items', ['infra_item_id'], unique=False)

    # The remaining ops were auto-generated drift. Guard everything.
    if 'dashboard_widgets' in existing and 'dashboard_widgets_created_by_fkey' in _fk_names('dashboard_widgets'):
        op.drop_constraint('dashboard_widgets_created_by_fkey', 'dashboard_widgets', type_='foreignkey')
        op.create_foreign_key(None, 'dashboard_widgets', 'users', ['created_by'], ['id'])

    if 'infra_items' in existing and 'infra_items_created_by_fkey' in _fk_names('infra_items'):
        op.drop_constraint('infra_items_created_by_fkey', 'infra_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('infra_items_created_by_fkey', 'infra_items', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'dashboard_widgets', type_='foreignkey')
    op.create_foreign_key('dashboard_widgets_created_by_fkey', 'dashboard_widgets', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_table('automation_rules',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('trigger_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='automation_rules_created_by_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='automation_rules_pkey')
    )
    op.create_index('ix_automation_rules_trigger_type', 'automation_rules', ['trigger_type'], unique=False)
    op.create_index('ix_automation_rules_is_enabled', 'automation_rules', ['is_enabled'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('engagement_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name='notifications_actor_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name='notifications_engagement_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_event_type', 'notifications', ['event_type'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('site_muted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_muted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_preferences_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notification_preferences_pkey'),
    sa.UniqueConstraint('user_id', 'event_type', name='uq_notification_pref_user_event')
    )
    op.create_index('ix_notification_preferences_user_id', 'notification_preferences', ['user_id'], unique=False)
    op.drop_index(op.f('ix_infra_vault_items_infra_item_id'), table_name='infra_vault_items')
    op.drop_table('infra_vault_items')
    op.drop_table('infra_vault_access')
    # ### end Alembic commands ###
