"""add attacker_nodes and attacker_node_edges tables

Revision ID: 8dbbee2919e4
Revises: 4e0eeb440642
Create Date: 2026-02-26 03:10:15.234585+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbbee2919e4'
down_revision: Union[str, None] = '4e0eeb440642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attacker_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('point_of_presence', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacker_nodes_engagement_id'), 'attacker_nodes', ['engagement_id'], unique=False)
    op.create_table('attacker_node_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attacker_node_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.String(length=255), nullable=False),
    sa.Column('target_node_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['attacker_node_id'], ['attacker_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacker_node_edges_attacker_node_id'), 'attacker_node_edges', ['attacker_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attacker_node_edges_attacker_node_id'), table_name='attacker_node_edges')
    op.drop_table('attacker_node_edges')
    op.drop_index(op.f('ix_attacker_nodes_engagement_id'), table_name='attacker_nodes')
    op.drop_table('attacker_nodes')
    # ### end Alembic commands ###
