"""add last_active to user

Revision ID: 6fc473943083
Revises: 20cddfaba85b
Create Date: 2026-01-31 06:55:24.380909+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc473943083'
down_revision: Union[str, None] = '20cddfaba85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('assets_updated_by_fkey', 'assets', type_='foreignkey')
    op.drop_constraint('assets_created_by_fkey', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assets', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('calendar_events', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('calendar_events_updated_by_fkey', 'calendar_events', type_='foreignkey')
    op.drop_constraint('calendar_events_created_by_fkey', 'calendar_events', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_events', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'calendar_events', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('engagements', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('engagements_created_by_fkey', 'engagements', type_='foreignkey')
    op.drop_constraint('engagements_updated_by_fkey', 'engagements', type_='foreignkey')
    op.create_foreign_key(None, 'engagements', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'engagements', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('evidence', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('evidence_updated_by_fkey', 'evidence', type_='foreignkey')
    op.drop_constraint('evidence_created_by_fkey', 'evidence', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'evidence', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('finding_templates', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('finding_templates_updated_by_fkey', 'finding_templates', type_='foreignkey')
    op.drop_constraint('finding_templates_created_by_fkey', 'finding_templates', type_='foreignkey')
    op.create_foreign_key(None, 'finding_templates', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'finding_templates', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('findings', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('findings_updated_by_fkey', 'findings', type_='foreignkey')
    op.drop_constraint('findings_created_by_fkey', 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'findings', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('testcases', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('testcases_created_by_fkey', 'testcases', type_='foreignkey')
    op.drop_constraint('testcases_updated_by_fkey', 'testcases', type_='foreignkey')
    op.create_foreign_key(None, 'testcases', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'testcases', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('last_active', sa.DateTime(), nullable=True))
    op.alter_column('vault_items', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('vault_items_created_by_fkey', 'vault_items', type_='foreignkey')
    op.drop_constraint('vault_items_updated_by_fkey', 'vault_items', type_='foreignkey')
    op.create_foreign_key(None, 'vault_items', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'vault_items', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vault_items', type_='foreignkey')
    op.drop_constraint(None, 'vault_items', type_='foreignkey')
    op.create_foreign_key('vault_items_updated_by_fkey', 'vault_items', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('vault_items_created_by_fkey', 'vault_items', 'users', ['created_by'], ['id'])
    op.alter_column('vault_items', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'last_active')
    op.drop_constraint(None, 'testcases', type_='foreignkey')
    op.drop_constraint(None, 'testcases', type_='foreignkey')
    op.create_foreign_key('testcases_updated_by_fkey', 'testcases', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('testcases_created_by_fkey', 'testcases', 'users', ['created_by'], ['id'])
    op.alter_column('testcases', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key('findings_created_by_fkey', 'findings', 'users', ['created_by'], ['id'])
    op.create_foreign_key('findings_updated_by_fkey', 'findings', 'users', ['updated_by'], ['id'])
    op.alter_column('findings', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'finding_templates', type_='foreignkey')
    op.drop_constraint(None, 'finding_templates', type_='foreignkey')
    op.create_foreign_key('finding_templates_created_by_fkey', 'finding_templates', 'users', ['created_by'], ['id'])
    op.create_foreign_key('finding_templates_updated_by_fkey', 'finding_templates', 'users', ['updated_by'], ['id'])
    op.alter_column('finding_templates', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key('evidence_created_by_fkey', 'evidence', 'users', ['created_by'], ['id'])
    op.create_foreign_key('evidence_updated_by_fkey', 'evidence', 'users', ['updated_by'], ['id'])
    op.alter_column('evidence', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.create_foreign_key('engagements_updated_by_fkey', 'engagements', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('engagements_created_by_fkey', 'engagements', 'users', ['created_by'], ['id'])
    op.alter_column('engagements', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.create_foreign_key('calendar_events_created_by_fkey', 'calendar_events', 'users', ['created_by'], ['id'])
    op.create_foreign_key('calendar_events_updated_by_fkey', 'calendar_events', 'users', ['updated_by'], ['id'])
    op.alter_column('calendar_events', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key('assets_created_by_fkey', 'assets', 'users', ['created_by'], ['id'])
    op.create_foreign_key('assets_updated_by_fkey', 'assets', 'users', ['updated_by'], ['id'])
    op.alter_column('assets', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
