"""comprehensive_audit_tracking

Revision ID: 3c15df371a14
Revises: add_created_by_tracking
Create Date: 2026-01-25 17:34:49.419250+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c15df371a14'
down_revision: Union[str, None] = 'add_created_by_tracking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('mitigations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_templates_category'), 'finding_templates', ['category'], unique=False)
    op.create_index(op.f('ix_finding_templates_title'), 'finding_templates', ['title'], unique=False)
    op.add_column('assets', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'assets', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'assets', 'users', ['updated_by'], ['id'])
    op.add_column('calendar_events', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'calendar_events', 'users', ['updated_by'], ['id'])
    op.add_column('engagements', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'engagements', 'users', ['updated_by'], ['id'])
    op.add_column('evidence', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('evidence', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('evidence', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('updated_by', sa.String(), nullable=True))
    
    # Data migration for existing evidence
    # 1. Update timestamps from uploaded_at
    op.execute("UPDATE evidence SET created_at = uploaded_at, updated_at = uploaded_at")
    # 2. Try to associate created_by with the finding's creator
    op.execute("UPDATE evidence SET created_by = findings.created_by FROM findings WHERE evidence.finding_id = findings.id")
    # 3. Fallback for any orphans (unlikely but safe)
    op.execute("UPDATE evidence SET created_by = (SELECT id FROM users LIMIT 1) WHERE created_by IS NULL")
    
    # Now set them to NOT NULL
    op.alter_column('evidence', 'created_at', nullable=False)
    op.alter_column('evidence', 'updated_at', nullable=False)
    op.alter_column('evidence', 'created_by', nullable=False)
    
    op.create_foreign_key(None, 'evidence', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'evidence', 'users', ['updated_by'], ['id'])
    op.drop_column('evidence', 'uploaded_at')
    op.add_column('findings', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'findings', 'users', ['updated_by'], ['id'])
    op.add_column('testcases', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'testcases', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'testcases', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testcases', type_='foreignkey')
    op.drop_constraint(None, 'testcases', type_='foreignkey')
    op.drop_column('testcases', 'updated_by')
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_column('findings', 'updated_by')
    op.add_column('evidence', sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_column('evidence', 'updated_by')
    op.drop_column('evidence', 'created_by')
    op.drop_column('evidence', 'updated_at')
    op.drop_column('evidence', 'created_at')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.drop_column('engagements', 'updated_by')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'updated_by')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'updated_by')
    op.drop_index(op.f('ix_finding_templates_title'), table_name='finding_templates')
    op.drop_index(op.f('ix_finding_templates_category'), table_name='finding_templates')
    op.drop_table('finding_templates')
    # ### end Alembic commands ###
