"""add_asset_tracking_fields

Revision ID: ce0d66f1543c
Revises: 3a9c3f0cfbb8
Create Date: 2026-01-25 04:58:58.320108+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_asset_tracking_fields

Revision ID: ce0d66f1543c
Revises: 3a9c3f0cfbb8
Create Date: 2026-01-25 04:58:58.320108+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0d66f1543c'
down_revision: Union[str, None] = '3a9c3f0cfbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('is_pwned', sa.Boolean(), nullable=True))
    op.add_column('assets', sa.Column('is_scanned', sa.Boolean(), nullable=True))
    op.add_column('assets', sa.Column('in_scope', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE assets SET is_pwned = false WHERE is_pwned IS NULL")
    op.execute("UPDATE assets SET is_scanned = false WHERE is_scanned IS NULL")
    op.execute("UPDATE assets SET in_scope = true WHERE in_scope IS NULL")
    
    # Make columns non-nullable
    op.alter_column('assets', 'is_pwned', nullable=False)
    op.alter_column('assets', 'is_scanned', nullable=False)
    op.alter_column('assets', 'in_scope', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'in_scope')
    op.drop_column('assets', 'is_scanned')
    op.drop_column('assets', 'is_pwned')
    # ### end Alembic commands ###
