"""add configurable_types table and convert enum columns to string

Revision ID: 753bbc1309ea
Revises: h2i3j4k5l6m7
Create Date: 2026-02-23 06:52:52.641574+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '753bbc1309ea'
down_revision: Union[str, None] = 'h2i3j4k5l6m7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurable_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'name', name='uq_configurable_type_category_name')
    )
    op.create_index(op.f('ix_configurable_types_category'), 'configurable_types', ['category'], unique=False)
    op.alter_column('assets', 'asset_type',
               existing_type=postgresql.ENUM('IP_ADDRESS', 'DOMAIN', 'URL', 'APPLICATION', 'SERVER', 'NETWORK', 'OTHER', name='assettype'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('cleanup_artifacts', 'artifact_type',
               existing_type=postgresql.ENUM('SSH_KEY', 'FILE', 'ACCOUNT', 'PERMISSION', 'BACKDOOR', 'IMPLANT', 'OTHER', name='cleanupartifacttype'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index('ix_evidence_testcase_id', table_name='evidence')
    op.alter_column('testcase_templates', 'category',
               existing_type=postgresql.ENUM('RECONNAISSANCE', 'SCANNING', 'EXPLOITATION', 'POST_EXPLOITATION', 'PRIVILEGE_ESCALATION', 'PERSISTENCE', 'LATERAL_MOVEMENT', 'WEB_APPLICATION', 'SOCIAL_ENGINEERING', 'PHYSICAL', 'OTHER', name='testcasecategory'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('testcases', 'category',
               existing_type=postgresql.ENUM('RECONNAISSANCE', 'SCANNING', 'EXPLOITATION', 'POST_EXPLOITATION', 'PRIVILEGE_ESCALATION', 'PERSISTENCE', 'LATERAL_MOVEMENT', 'WEB_APPLICATION', 'SOCIAL_ENGINEERING', 'PHYSICAL', 'OTHER', name='testcasecategory'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('vault_items', 'item_type',
               existing_type=postgresql.ENUM('CREDENTIAL', 'KEY', 'FILE', 'NOTE', name='vaultitemtype'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index('ix_version_history_entity', table_name='version_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_version_history_entity', 'version_history', ['entity_type', 'entity_id', 'version'], unique=True)
    op.alter_column('vault_items', 'item_type',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('CREDENTIAL', 'KEY', 'FILE', 'NOTE', name='vaultitemtype'),
               existing_nullable=False)
    op.alter_column('testcases', 'category',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('RECONNAISSANCE', 'SCANNING', 'EXPLOITATION', 'POST_EXPLOITATION', 'PRIVILEGE_ESCALATION', 'PERSISTENCE', 'LATERAL_MOVEMENT', 'WEB_APPLICATION', 'SOCIAL_ENGINEERING', 'PHYSICAL', 'OTHER', name='testcasecategory'),
               existing_nullable=False)
    op.alter_column('testcase_templates', 'category',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('RECONNAISSANCE', 'SCANNING', 'EXPLOITATION', 'POST_EXPLOITATION', 'PRIVILEGE_ESCALATION', 'PERSISTENCE', 'LATERAL_MOVEMENT', 'WEB_APPLICATION', 'SOCIAL_ENGINEERING', 'PHYSICAL', 'OTHER', name='testcasecategory'),
               existing_nullable=False)
    op.create_index('ix_evidence_testcase_id', 'evidence', ['testcase_id'], unique=False)
    op.alter_column('cleanup_artifacts', 'artifact_type',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('SSH_KEY', 'FILE', 'ACCOUNT', 'PERMISSION', 'BACKDOOR', 'IMPLANT', 'OTHER', name='cleanupartifacttype'),
               existing_nullable=False)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('IP_ADDRESS', 'DOMAIN', 'URL', 'APPLICATION', 'SERVER', 'NETWORK', 'OTHER', name='assettype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_configurable_types_category'), table_name='configurable_types')
    op.drop_table('configurable_types')
    # ### end Alembic commands ###
