"""add permission system tables

Revision ID: df63f91f5dac
Revises: bcd94aa9b80a
Create Date: 2026-02-01 04:30:19.154181+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df63f91f5dac'
down_revision: Union[str, None] = 'bcd94aa9b80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['engagement_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('group_permissions',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_permissions')
    op.drop_table('engagement_role_permissions')
    # ### end Alembic commands ###
