"""add finding_reviews

Revision ID: f996904ad75d
Revises: 435b0206d1c9
Create Date: 2026-09-08 01:28:06.952268+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f996904ad75d'
down_revision: Union[str, None] = '435b0206d1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'reviewer_id', name='uq_finding_review_reviewer')
    )
    op.create_index(op.f('ix_finding_reviews_finding_id'), 'finding_reviews', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_reviews_reviewer_id'), 'finding_reviews', ['reviewer_id'], unique=False)
    # (autogenerate also flagged unrelated pre-existing index drift — omitted.)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_reviews_reviewer_id'), table_name='finding_reviews')
    op.drop_index(op.f('ix_finding_reviews_finding_id'), table_name='finding_reviews')
    op.drop_table('finding_reviews')
    # ### end Alembic commands ###
