"""update_evidence_model_for_engagement_attachments

Revision ID: 8278441b8f89
Revises: 3c15df371a14
Create Date: 2026-01-25 18:44:01.460631+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8278441b8f89'
down_revision: Union[str, None] = '3c15df371a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('engagement_id', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('include_in_report', sa.Boolean(), nullable=True))
    op.alter_column('evidence', 'finding_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'evidence', 'engagements', ['engagement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.alter_column('evidence', 'finding_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('evidence', 'include_in_report')
    op.drop_column('evidence', 'engagement_id')
    # ### end Alembic commands ###
