"""add_report_layouts

Revision ID: de6c156f8aa1
Revises: f6a7b8c9d0e1
Create Date: 2026-02-08 05:20:23.163096+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6c156f8aa1'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_layout_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_layout_templates_name'), 'report_layout_templates', ['name'], unique=False)
    op.create_table('report_layout_template_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('section_type', sa.Enum('text', 'findings', 'testcases', name='sectiontype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['report_layout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_layout_template_sections_template_id'), 'report_layout_template_sections', ['template_id'], unique=False)
    op.create_table('report_layouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_layouts_engagement_id'), 'report_layouts', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_report_layouts_name'), 'report_layouts', ['name'], unique=False)
    op.create_table('report_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_layout_id', sa.String(), nullable=False),
    sa.Column('section_type', sa.Enum('text', 'findings', 'testcases', name='sectiontype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_layout_id'], ['report_layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sections_report_layout_id'), 'report_sections', ['report_layout_id'], unique=False)
    op.drop_constraint('runbooks_created_by_fkey', 'runbooks', type_='foreignkey')
    op.drop_constraint('runbooks_updated_by_fkey', 'runbooks', type_='foreignkey')
    op.create_foreign_key(None, 'runbooks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'runbooks', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runbooks', type_='foreignkey')
    op.drop_constraint(None, 'runbooks', type_='foreignkey')
    op.create_foreign_key('runbooks_updated_by_fkey', 'runbooks', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('runbooks_created_by_fkey', 'runbooks', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_report_sections_report_layout_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_report_layouts_name'), table_name='report_layouts')
    op.drop_index(op.f('ix_report_layouts_engagement_id'), table_name='report_layouts')
    op.drop_table('report_layouts')
    op.drop_index(op.f('ix_report_layout_template_sections_template_id'), table_name='report_layout_template_sections')
    op.drop_table('report_layout_template_sections')
    op.drop_index(op.f('ix_report_layout_templates_name'), table_name='report_layout_templates')
    op.drop_table('report_layout_templates')
    # ### end Alembic commands ###
