"""align_schema_drift_cleanup

Revision ID: b80ed9333c61
Revises: f4a2c8e1d3b5
Create Date: 2026-06-04 05:47:49.955830+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b80ed9333c61'
down_revision: Union[str, None] = 'f4a2c8e1d3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finding_attack_techniques', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_finding_attack_techniques_technique', table_name='finding_attack_techniques')
    op.drop_index('ix_markdown_images_engagement', table_name='markdown_images')
    op.create_index(op.f('ix_markdown_images_engagement_id'), 'markdown_images', ['engagement_id'], unique=False)
    op.alter_column('spray_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('spray_campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_spray_campaigns_engagement', table_name='spray_campaigns')
    op.drop_constraint('spray_campaigns_updated_by_fkey', 'spray_campaigns', type_='foreignkey')
    op.drop_constraint('spray_campaigns_created_by_fkey', 'spray_campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'spray_campaigns', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'spray_campaigns', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_spray_results_campaign', table_name='spray_results')
    op.drop_index('ix_spray_results_result', table_name='spray_results')
    op.alter_column('testcase_attack_techniques', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_testcase_attack_techniques_technique', table_name='testcase_attack_techniques')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_testcase_attack_techniques_technique', 'testcase_attack_techniques', ['technique_id'], unique=False)
    op.alter_column('testcase_attack_techniques', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_spray_results_result', 'spray_results', ['result'], unique=False)
    op.create_index('ix_spray_results_campaign', 'spray_results', ['campaign_id'], unique=False)
    op.drop_constraint(None, 'spray_campaigns', type_='foreignkey')
    op.drop_constraint(None, 'spray_campaigns', type_='foreignkey')
    op.create_foreign_key('spray_campaigns_created_by_fkey', 'spray_campaigns', 'users', ['created_by'], ['id'])
    op.create_foreign_key('spray_campaigns_updated_by_fkey', 'spray_campaigns', 'users', ['updated_by'], ['id'])
    op.create_index('ix_spray_campaigns_engagement', 'spray_campaigns', ['engagement_id'], unique=False)
    op.alter_column('spray_campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('spray_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_markdown_images_engagement_id'), table_name='markdown_images')
    op.create_index('ix_markdown_images_engagement', 'markdown_images', ['engagement_id'], unique=False)
    op.create_index('ix_finding_attack_techniques_technique', 'finding_attack_techniques', ['technique_id'], unique=False)
    op.alter_column('finding_attack_techniques', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
