"""add users.saml_subject

Revision ID: f34670cca6d7
Revises: 217ed37919e5
Create Date: 2026-06-22 22:15:40.853675+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34670cca6d7'
down_revision: Union[str, None] = '217ed37919e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('saml_subject', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_users_saml_subject'), 'users', ['saml_subject'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_saml_subject'), table_name='users')
    op.drop_column('users', 'saml_subject')
    # ### end Alembic commands ###
