"""track_missing_tables

Revision ID: 9d9b13ccdaea
Revises: bd421d1080ad
Create Date: 2026-03-31 05:21:48.518735+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9b13ccdaea'
down_revision: Union[str, None] = '38e74addb1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = inspector.get_table_names()

    if 'plugin_settings' not in existing:
        op.create_table('plugin_settings',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('plugin_id', sa.String(length=100), nullable=False),
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('is_secret', sa.Boolean(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sqlite_autoincrement=False
        )
    if 'plugin_settings' not in existing:
        op.create_index(op.f('ix_plugin_settings_plugin_id'), 'plugin_settings', ['plugin_id'], unique=False)
    if 'automation_rules' not in existing:
        op.create_table('automation_rules',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('trigger_type', sa.String(length=64), nullable=False),
        sa.Column('conditions', sa.JSON(), nullable=False),
        sa.Column('actions', sa.JSON(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('created_by', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
        sa.Column('trigger_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'automation_rules' not in existing:
        op.create_index(op.f('ix_automation_rules_trigger_type'), 'automation_rules', ['trigger_type'], unique=False)
    if 'client_user_access' not in existing:
        op.create_table('client_user_access',
        sa.Column('client_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('granted_by', sa.String(), nullable=True),
        sa.Column('granted_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('client_id', 'user_id')
        )
    if 'finding_assets' not in existing:
        op.create_table('finding_assets',
        sa.Column('finding_id', sa.String(), nullable=False),
        sa.Column('asset_id', sa.String(), nullable=False),
        sa.Column('port_ids', sa.Text(), nullable=True),
        sa.Column('remediated', sa.Boolean(), nullable=False),
        sa.Column('remediated_at', sa.DateTime(), nullable=True),
        sa.Column('remediated_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['remediated_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('finding_id', 'asset_id')
        )
    if 'infra_item_findings' not in existing:
        op.create_table('infra_item_findings',
        sa.Column('infra_item_id', sa.String(), nullable=False),
        sa.Column('finding_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['infra_item_id'], ['infra_items.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('infra_item_id', 'finding_id')
        )
    if 'infra_item_notes' not in existing:
        op.create_table('infra_item_notes',
        sa.Column('infra_item_id', sa.String(), nullable=False),
        sa.Column('note_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['infra_item_id'], ['infra_items.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('infra_item_id', 'note_id')
        )
    if 'infra_item_testcases' not in existing:
        op.create_table('infra_item_testcases',
        sa.Column('infra_item_id', sa.String(), nullable=False),
        sa.Column('testcase_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['infra_item_id'], ['infra_items.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('infra_item_id', 'testcase_id')
        )
    if 'testcase_assets' not in existing:
        op.create_table('testcase_assets',
        sa.Column('testcase_id', sa.String(), nullable=False),
        sa.Column('asset_id', sa.String(), nullable=False),
        sa.Column('port_ids', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('testcase_id', 'asset_id')
        )
    if 'testcase_tags' not in existing:
        op.create_table('testcase_tags',
        sa.Column('testcase_id', sa.String(), nullable=False),
        sa.Column('tag_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('testcase_id', 'tag_id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = inspector.get_table_names()

    op.drop_table('testcase_tags')
    op.drop_table('testcase_assets')
    op.drop_table('infra_item_testcases')
    op.drop_table('infra_item_notes')
    op.drop_table('infra_item_findings')
    op.drop_table('finding_assets')
    op.drop_table('client_user_access')
    op.drop_index(op.f('ix_automation_rules_trigger_type'), table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('ix_plugin_settings_plugin_id'), table_name='plugin_settings')
    op.drop_table('plugin_settings')
    # ### end Alembic commands ###
