"""add activity_pings

Revision ID: 435b0206d1c9
Revises: a7c1e9d2b4f6
Create Date: 2026-09-08 00:37:56.063791+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435b0206d1c9'
down_revision: Union[str, None] = 'a7c1e9d2b4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_pings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_pings_engagement_id'), 'activity_pings', ['engagement_id'], unique=False)
    op.create_index('ix_activity_pings_rtype_created', 'activity_pings', ['resource_type', 'created_at'], unique=False)
    op.create_index('ix_activity_pings_user_created', 'activity_pings', ['user_id', 'created_at'], unique=False)
    # NOTE: autogenerate also flagged drops of ix_engagement_tags_tag_id and
    # ix_stats_pages_position — pre-existing model/DB drift unrelated to this
    # change; intentionally NOT included here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_pings_user_created', table_name='activity_pings')
    op.drop_index('ix_activity_pings_rtype_created', table_name='activity_pings')
    op.drop_index(op.f('ix_activity_pings_engagement_id'), table_name='activity_pings')
    op.drop_table('activity_pings')
    # ### end Alembic commands ###
