"""add cleanup artifacts tables

Revision ID: 9b4e0d08d58c
Revises: b3c4d5e6f7g8
Create Date: 2026-02-09 02:41:56.794465+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4e0d08d58c'
down_revision: Union[str, None] = 'b3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artifact_type', sa.Enum('SSH_KEY', 'FILE', 'ACCOUNT', 'PERMISSION', 'BACKDOOR', 'IMPLANT', 'OTHER', name='cleanupartifacttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLEANED', 'PARTIALLY_CLEANED', 'NOT_APPLICABLE', name='cleanupartifactstatus'), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cleanup_notes', sa.Text(), nullable=True),
    sa.Column('cleaned_at', sa.DateTime(), nullable=True),
    sa.Column('cleaned_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cleaned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleanup_artifacts_engagement_id'), 'cleanup_artifacts', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_cleanup_artifacts_title'), 'cleanup_artifacts', ['title'], unique=False)
    op.create_table('cleanup_artifact_findings',
    sa.Column('cleanup_artifact_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cleanup_artifact_id'], ['cleanup_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cleanup_artifact_id', 'finding_id')
    )
    op.create_table('cleanup_artifact_testcases',
    sa.Column('cleanup_artifact_id', sa.String(), nullable=False),
    sa.Column('testcase_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cleanup_artifact_id'], ['cleanup_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cleanup_artifact_id', 'testcase_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleanup_artifact_testcases')
    op.drop_table('cleanup_artifact_findings')
    op.drop_index(op.f('ix_cleanup_artifacts_title'), table_name='cleanup_artifacts')
    op.drop_index(op.f('ix_cleanup_artifacts_engagement_id'), table_name='cleanup_artifacts')
    op.drop_table('cleanup_artifacts')
    # ### end Alembic commands ###
