"""deepen_report_theme_controls

Revision ID: a1f2c3d4e5b6
Revises: 293665bb09ce
Create Date: 2026-06-04 00:30:00.000000+00:00

Adds the deepened appearance controls to report_themes: themeable severity
colors, table style tokens, header/footer zones, and cover metadata. All
columns are nullable — the PDF generator falls back to its built-in _DEFAULTS
when a column is null, so existing themes render unchanged.

Hand-written (not autogenerated) to keep it scoped to these columns and avoid
pulling in unrelated pre-existing schema drift.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a1f2c3d4e5b6'
down_revision: Union[str, None] = '293665bb09ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_COLUMNS = [
    ('severity_critical_color', sa.String(length=9)),
    ('severity_high_color', sa.String(length=9)),
    ('severity_medium_color', sa.String(length=9)),
    ('severity_low_color', sa.String(length=9)),
    ('severity_info_color', sa.String(length=9)),
    ('table_zebra_enabled', sa.Boolean()),
    ('table_alt_row_bg', sa.String(length=9)),
    ('table_grid_color', sa.String(length=9)),
    ('header_left', sa.String(length=255)),
    ('header_center', sa.String(length=255)),
    ('header_right', sa.String(length=255)),
    ('footer_left', sa.String(length=255)),
    ('footer_center', sa.String(length=255)),
    ('footer_right', sa.String(length=255)),
    ('show_page_x_of_y', sa.Boolean()),
    ('cover_template', sa.String(length=40)),
    ('cover_subtitle', sa.String(length=500)),
    ('cover_background_base64', sa.Text()),
    ('report_reference', sa.String(length=120)),
    ('report_version', sa.String(length=40)),
]


def upgrade() -> None:
    for name, coltype in _COLUMNS:
        op.add_column('report_themes', sa.Column(name, coltype, nullable=True))


def downgrade() -> None:
    for name, _ in reversed(_COLUMNS):
        op.drop_column('report_themes', name)
