"""add scan_imports

Revision ID: a05559c23e41
Revises: f6a0d3e8c4b2
Create Date: 2026-08-02 20:57:30.394431+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05559c23e41'
down_revision: Union[str, None] = 'f6a0d3e8c4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_imports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('source_tool', sa.String(length=50), nullable=False),
    sa.Column('source_format', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('scanner', sa.String(length=120), nullable=True),
    sa.Column('scanner_version', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.String(length=60), nullable=True),
    sa.Column('finished_at', sa.String(length=60), nullable=True),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('hosts_total', sa.Integer(), nullable=True),
    sa.Column('hosts_up', sa.Integer(), nullable=True),
    sa.Column('hosts_down', sa.Integer(), nullable=True),
    sa.Column('assets_created', sa.Integer(), nullable=True),
    sa.Column('assets_merged', sa.Integer(), nullable=True),
    sa.Column('findings_created', sa.Integer(), nullable=True),
    sa.Column('ports_added', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_imports_engagement_id'), 'scan_imports', ['engagement_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_engagement_tags_tag_id and
    # ix_stats_pages_position — pre-existing model/DB drift unrelated to this
    # change. Deliberately omitted so this migration only adds scan_imports.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_scan_imports_engagement_id'), table_name='scan_imports')
    op.drop_table('scan_imports')
