"""add_testcase_templates

Revision ID: 0b2502eb8297
Revises: 9fa1829f5bf9
Create Date: 2026-01-26 02:39:12.596772+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '0b2502eb8297'
down_revision: Union[str, None] = '9fa1829f5bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcase_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', postgresql.ENUM('RECONNAISSANCE', 'SCANNING', 'EXPLOITATION', 'POST_EXPLOITATION', 'PRIVILEGE_ESCALATION', 'PERSISTENCE', 'LATERAL_MOVEMENT', 'WEB_APPLICATION', 'SOCIAL_ENGINEERING', 'PHYSICAL', 'OTHER', name='testcasecategory', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testcase_templates_title'), 'testcase_templates', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testcase_templates_title'), table_name='testcase_templates')
    op.drop_table('testcase_templates')
    # ### end Alembic commands ###

