"""add attack_graph_layouts table

Revision ID: 4e0eeb440642
Revises: 09422adc9dec
Create Date: 2026-02-25 06:39:18.252443+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0eeb440642'
down_revision: Union[str, None] = '09422adc9dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_graph_layouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('positions', sa.Text(), nullable=False),
    sa.Column('pinned_by', sa.String(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_graph_layouts_engagement_id'), 'attack_graph_layouts', ['engagement_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_graph_layouts_engagement_id'), table_name='attack_graph_layouts')
    op.drop_table('attack_graph_layouts')
    # ### end Alembic commands ###
