"""add_report_themes

Revision ID: 664856e9c616
Revises: de6c156f8aa1
Create Date: 2026-02-08 06:17:47.583417+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664856e9c616'
down_revision: Union[str, None] = 'de6c156f8aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_themes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=9), nullable=False),
    sa.Column('secondary_color', sa.String(length=9), nullable=False),
    sa.Column('header_text_color', sa.String(length=9), nullable=False),
    sa.Column('body_text_color', sa.String(length=9), nullable=False),
    sa.Column('table_header_bg', sa.String(length=9), nullable=False),
    sa.Column('table_header_text', sa.String(length=9), nullable=False),
    sa.Column('font_family', sa.String(length=50), nullable=False),
    sa.Column('font_size_body', sa.Integer(), nullable=False),
    sa.Column('font_size_heading', sa.Integer(), nullable=False),
    sa.Column('logo_base64', sa.Text(), nullable=True),
    sa.Column('show_page_numbers', sa.Boolean(), nullable=False),
    sa.Column('show_cover_page', sa.Boolean(), nullable=False),
    sa.Column('cover_title', sa.String(length=500), nullable=False),
    sa.Column('header_text', sa.String(length=500), nullable=True),
    sa.Column('footer_text', sa.String(length=500), nullable=True),
    sa.Column('page_size', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_themes_name'), 'report_themes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_themes_name'), table_name='report_themes')
    op.drop_table('report_themes')
    # ### end Alembic commands ###
